--- Foreign Keys Contraints : 

-- SalesFact table foreign keys
ALTER TABLE SalesFact
ADD CONSTRAINT FK_SALESFACT_Product
FOREIGN KEY (ProductID) REFERENCES ProductDim(ProductID)
ON DELETE CASCADE;

ALTER TABLE SalesFact
ADD CONSTRAINT FK_SALESFACT_Customer
FOREIGN KEY (CustomerID) REFERENCES CustomerDim(CustomerID)
ON DELETE CASCADE;

ALTER TABLE SalesFact
ADD CONSTRAINT FK_SALESFACT_Date
FOREIGN KEY (DateID) REFERENCES DateDim(DateID)
ON DELETE CASCADE;

-- InventoryFact table foreign keys

ALTER TABLE InventoryFact
ADD CONSTRAINT FK_INVENTORYFACT_Date
FOREIGN KEY (DateID) REFERENCES DateDim(DateID)
ON DELETE CASCADE;

ALTER TABLE InventoryFact
ADD CONSTRAINT FK_INVENTORYFACT_Product
FOREIGN KEY (ProductID) REFERENCES ProductDim(ProductID)
ON DELETE CASCADE;

ALTER TABLE InventoryFact
ADD CONSTRAINT FK_INVENTORYFACT_Shipper
FOREIGN KEY (ShipperID) REFERENCES ShipperDim(ShipperID)
ON DELETE CASCADE;

ALTER TABLE InventoryFact
ADD CONSTRAINT FK_INVENTORYFACT_Supplier
FOREIGN KEY (SupplierID) REFERENCES SupplierDim(SupplierID)
ON DELETE CASCADE;
