DROP TABLE DBO.Inventory ;
DROP TABLE DBO.Supplier ;
DROP TABLE DBO.Date ;
DROP TABLE DBO.Product ;


ALTER TABLE Inventory
ADD CONSTRAINT FK_INVENTORY_Product
FOREIGN KEY (ProductID) REFERENCES dbo.Product(ProductID)
ON DELETE CASCADE;

ALTER TABLE Inventory
ADD CONSTRAINT FK_INVENTORY_Date
FOREIGN KEY (DateID) REFERENCES Date(DateID)
ON DELETE CASCADE;

ALTER TABLE Inventory
ADD CONSTRAINT FK_INVENTORY_Supplier
FOREIGN KEY (SupplierID) REFERENCES Supplier(SupplierID)
ON DELETE CASCADE;