DROP TABLE DBO.Customer ;
DROP TABLE DBO.[Date] ;
DROP TABLE DBO.[Sales] ;
DROP TABLE DBO.[Product] ;
DROP TABLE DBO.[Shipper] ;

ALTER TABLE Sales
ADD CONSTRAINT FK_SALES_Customer
FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
ON DELETE CASCADE;

ALTER TABLE Sales
ADD CONSTRAINT FK_SALES_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE CASCADE;


ALTER TABLE Sales
ADD CONSTRAINT FK_SALES_Date
FOREIGN KEY (DateID) REFERENCES Date(DateID)
ON DELETE CASCADE;

ALTER TABLE Sales
ADD CONSTRAINT FK_Sales_Shipper
FOREIGN KEY (ShipperID) REFERENCES Shipper(ShipperID)
ON DELETE CASCADE;
